#############
# Development
#############

version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment: 
      MONGO_URI: mongodb://mongo:27017/test
      JWT_SECRET: 1234
      COOKIE_SECRET: 1234
      NODE_ENV: test
    command: npm run test; npm run test:e2e;
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27018:27017'
