#############
# Development
#############

version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment: 
      MONGO_URI: mongodb://mongo:27017/test
      JWT_SECRET: 1234
      COOKIE_SECRET: 1234
      NODE_ENV: test
    command: |
      /bin/sh -c "npm run test ; npm run test:e2e"
    depends_on:
      - mongo

  mongo:
    image: mongo
    command: --replSet rs0
    ports:
      - '27018:27017'
  mongo-setup:
    image: mongo:4.2
    command: >
      bash -c "
        sleep 10 &&
        mongo --host mongo --eval \"
          rs.initiate({
            _id: 'rs0',
            members: [ { _id: 0, host: 'localhost:27017' } ]
          })
        \"
      "
    depends_on:
      - mongo
