name: ✨ Request Feature
description: 기능 건의
title: "✨ Request: "
labels:
  - enhancement
assignees:
  - Yoowatney

body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: 어떤 기능 개선을 할까요?
      placeholder: "Describe your feature"
    validations:
      required: true
