version: "3.7"

services:
  influxdb:
    image: influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8088:8088"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=admin
      - INFLUXDB_ADMIN_USER_TOKEN=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=test
    volumes:
      - influxdb-storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      # - ./grafana-data:/etc/grafana/provisioning
      - ./grafana-data/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-data/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb
  k6:
    image: grafana/k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/test
    volumes:
      - ./k6/scripts:/scripts

volumes:
  influxdb-storage:
  grafana-storage:
